language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

cache: apt


addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - graphviz
    - libfftw3-dev
    - libmpfr-dev
    - libcgal-dev


before_install:


########
# Deps.
########
before_script:
   - if [ $TRAVIS_OS_NAME == osx ]; then brew install fftw cgal; echo "All deps ok."; fi


############
# Main rules
############
script:
  - mkdir build ; cd build
  - cmake .. -DUSE_FFTW=true -DUSE_CIMG=true -DUSE_MPFR=true 
  - make
  - make test


###########
## Building the documentation
###########
after_success:
